[URL]
GameName=ProjectIGI_Remake

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/ThirdPerson/Lvl_ThirdPerson.Lvl_ThirdPerson
GameDefaultMap=/Game/ThirdPerson/Lvl_ThirdPerson.Lvl_ThirdPerson
GlobalDefaultGameMode=/Script/ProjectIGI_Remake.IGIGameModeBase

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_ThirdPersonBP",NewGameName="/Script/ProjectIGI_Remake")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_ThirdPersonBP",NewGameName="/Script/ProjectIGI_Remake")

[/Script/Engine.PhysicsSettings]
+PhysicalSurfaces=(Type=SurfaceType1,Name="Dirt")
+PhysicalSurfaces=(Type=SurfaceType2,Name="Mud")
+PhysicalSurfaces=(Type=SurfaceType3,Name="Snow")
+PhysicalSurfaces=(Type=SurfaceType4,Name="Sand")
+PhysicalSurfaces=(Type=SurfaceType5,Name="Grass")
+PhysicalSurfaces=(Type=SurfaceType6,Name="Concrete")
+PhysicalSurfaces=(Type=SurfaceType7,Name="Metal")
+PhysicalSurfaces=(Type=SurfaceType8,Name="Water")


[SystemSettings]
; Thermal/infrared vision uses Custom Stencil to identify opt-in heat signatures.
r.CustomDepth=3
